### ISSUE TITLE
[问题] docker启动时配置的PROXY_URL地址只能填写ip，不能填写域名

### ISSUE THREAD

**Issue by cddc** [Yidadaa/ChatGPT-Next-Web#1073]
**反馈须知**
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
采用docker部署的方式，启动docker时配置的PROXY_URL只能填写ip，不能填写域名。
如果填写域名，则会在docker logs里有报错信息：
``` shell
xray_1  | [proxychains] config file found: /etc/proxychains.conf
xray_1  | [proxychains] preloading /usr/lib/libproxychains4.so
xray_1  | proxy XXXX.YYY.ZZZ has invalid value or is not numeric
xray_1  | non-numeric ips are only allowed under the following circumstances:
xray_1  | chaintype == strict (true), proxy is not first in list (false), proxy_dns active (thread)
```
从log报错中看出，大概应该是没有配置针对代理域名的dns解析导致的，但是**我不知道应该怎么在这个docker理配置proxy_dns**。

**如何复现**
以下是docker-compose.yml
``` yaml
version: '3'
services:
  xray:
    image: yidadaa/chatgpt-next-web:v1.9.9
    ports:
      - "3000:3000"
    environment:
      OPENAI_API_KEY: .....
      CODE: ....
      PROXY_URL: http://XXX.YYY.ZZZ:1000
    hostname: chatgpt-next-web
```

**截图**
以下是docker logs的报错信息
```shell
xray_1  | strict_chain
xray_1  | proxy_dns
xray_1  | remote_dns_subnet 224
xray_1  | tcp_read_time_out 15000
xray_1  | tcp_connect_time_out 8000
xray_1  | [ProxyList]
xray_1  | http XXX.YYY.ZZZ 1000
xray_1  | [proxychains] config file found: /etc/proxychains.conf
xray_1  | [proxychains] preloading /usr/lib/libproxychains4.so
xray_1  | proxy XXX.YYY.ZZZ has invalid value or is not numeric
xray_1  | non-numeric ips are only allowed under the following circumstances:
xray_1  | chaintype == strict (true), proxy is not first in list (false), proxy_dns active (thread)
xray_1  | 
```

**一些必要的信息**
 - 将XXX.YYY.ZZZ域名，换成解析好的ip，则docker可以正常启动，服务运行正常。
