### ISSUE TITLE
[Bug] errno: -3001是什么情况啊

### ISSUE THREAD

**Issue by rumosky** [Yidadaa/ChatGPT-Next-Web#1852]
首先，说一下，我在QQ群里问了十年，没人理我，没人回复，都在自顾自的聊天，或者卖账号，卖key，不是我看不到先在群里问这个提示。

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
我用国内的腾讯云服务器搭建的docker版本，使用的是官方的docker镜像和命令。反代之后，用域名访问，报错，提示下面的内容：
```
{
  "cause": {
    "errno": -3001,
    "code": "EAI_AGAIN",
    "syscall": "getaddrinfo",
    "hostname": "oa.api2d.net"
  }
}
```

我使用的是api2d.com这个提供的代理API，我通过chat酱本地使用是正常的，用你们官网的vercel搭建，用这个api2d的密钥是正常的。
而且，api2d本身就是国内的代理，我用国内的服务器理论上是可以访问的，不需要用国外的服务器。

**如何复现**
就正常搭建，docker启动之后设置了反代，也可以正常访问，但是输入访问密码之后提示上面那个错误。这里我想问一下，docker反代里的命令，BASE_URL后面带不带协议头，因为vercel里的环境变量是不写协议头的，我把这两个都试了，还是显示上面那个错误

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。

**一些必要的信息**
 - 系统：服务器是CentOS7.9 x64，本地电脑是windows11 22H2
 - 浏览器：Chrome 114.0.5735.110
 - 版本： 114.0.5735.110
 - 部署方式：国内腾讯云服务器docker部署

**Comment by Yidadaa** [comment]
BASE_URL 带上 `https://`

**Comment by rumosky** [comment]
> BASE_URL 带上 `https://`

我带了，还是这个问题，好像是服务器访问不到这个BASE_URL主机，我用host宿主机网络，也不行。但是容器的日志，显示是正常启动的，Listening on port 3000 url: http://970b52add58c:3000，这个是日志

**Comment by rumosky** [comment]
```
version: '3'
services:
  chatgpt-next-web:
    image: yidadaa/chatgpt-next-web
    container_name: chatgpt-next-web
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=xxxx
      - CODE=xxxxx
      - BASE_URL=https://oa.api2d.net

```

这个是我用的docker-compose文件，刚刚试了，日志是上面那个，但访问之后会提示-3001错误
