### ISSUE TITLE
[Bug] chat/completions对话显示错误

### ISSUE THREAD

**Issue by tiyee** [Yidadaa/ChatGPT-Next-Web#1904]
**Describe the bug**
如图所示，我是用docker-compose部署的，一个docker部署的next-web，另一个docker部署了一个代理，然后通过这个代理转发的。配置如下

```yaml

  next-ui:
    image: yidadaa/chatgpt-next-web:latest
    container_name: next-ui
    restart: on-failure
    depends_on:
      - api
    ports:
      - "127.0.0.1:8718:3000"
    environment:
      TZ: Asia/Shanghai
      OPENAI_API_KEY: test111111111111111111
      BASE_URL: "http://api:7718"
      CODE: test222222222222
      HIDE_USER_API_KEY: 1

```
[点击查看图片](https://img.tiyee.cn/u/m2ysn3.png)
返回的数据如下
```
data: {"id":"chatcmpl-7QRgJDv6GupFshi2e2DEuzr4XCtjA","object":"chat.completion.chunk","created":1686537291,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"role":"assistant"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7QRgJDv6GupFshi2e2DEuzr4XCtjA","object":"chat.completion.chunk","created":1686537291,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":"Hello"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7QRgJDv6GupFshi2e2DEuzr4XCtjA","object":"chat.completion.chunk","created":1686537291,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" World"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7QRgJDv6GupFshi2e2DEuzr4XCtjA","object":"chat.completion.chunk","created":1686537291,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{},"index":0,"finish_reason":"stop"}]}

data: [DONE]


```
