### ISSUE TITLE
[Feature] 是否考虑开发支持Web API  OPENAI_ACCESS_TOKEN功能?

### ISSUE THREAD

**Issue by walkchen9** [Yidadaa/ChatGPT-Next-Web#2216]
是否考虑开发支持Web API  OPENAI_ACCESS_TOKEN功能?

**Comment by dengchangdong** [comment]
部署https://github.com/acheong08/ChatGPT-to-API，配置accessToken。
base url填写你的反代地址，不配置api key。

**Comment by walkchen9** [comment]
> 

如果开通了Plus 支持gpt4吗？

**Comment by walkchen9** [comment]
> 部署[https://github.com/acheong08/ChatGPT-to-API，配置accessToken。](https://github.com/acheong08/ChatGPT-to-API%EF%BC%8C%E9%85%8D%E7%BD%AEaccessToken%E3%80%82) base url填写你的反代地址，不配置api key。

没明白怎么用docker部署，只要在 docker-compose 文件上配置puid就可以吗？Access_token要配置到哪里？

**Comment by dengchangdong** [comment]
> > 部署[https://github.com/acheong08/ChatGPT-to-API，配置accessToken。](https://github.com/acheong08/ChatGPT-to-API%EF%BC%8C%E9%85%8D%E7%BD%AEaccessToken%E3%80%82) base url填写你的反代地址，不配置api key。
> 
> 没明白怎么用docker部署，只要在 docker-compose 文件上配置puid就可以吗？Access_token要配置到哪里？

1、部署 [linweiyuan/go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api) 绕过cloudflare验证；
2、部署 [acheong08/ChatGPT-to-API](https://github.com/acheong08/ChatGPT-to-API) 配置 `accesstoken` ,生成一个 fakeAPI;

docker-compose.yml 代码如下：
```
  go-chatgpt-api:
    image: linweiyuan/go-chatgpt-api
    environment:
      - TZ=Asia/Shanghai
      - GIN=release
    restart: unless-stopped


  chatgpt-to-api:
    image: acheong08/chatgpt-to-api
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      GIN_MODE: release
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      ADMIN_PASSWORD: password
      API_REVERSE_PROXY: http://go-chatgpt-api:8080/chatgpt/backend-api/conversation
    depends_on:
      - go-chatgpt-api
```
3、部署 [ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web) ， 变量只需要填写  `BASE_URL = fakeAPI ip:port` 即可。
