### ISSUE TITLE
Docker 运行时，OPENAI_API_KEY环境变量无效

### ISSUE THREAD

**Issue by zinohome** [Yidadaa/ChatGPT-Next-Web#265]
docker 运行时，即使输入了OPENAI_API_KEY环境变量，在web端仍然提示需要输入OPENAI_API_KEY，如何解决？

**Comment by Yidadaa** [comment]
请提供执行的 docker 命令。

**Comment by lialosiu** [comment]
我这里也可以确认这个问题

docker compose.yaml
```
services:
  chatgpt:
    image: yidadaa/chatgpt-next-web
    environment:
      - OPENAI_API_KEY="sk-****"
      - CODE="****"
    ports:
      - 8083:3000
```



exec进入docker容器中，env查看环境变量
```
/app # env
NODE_VERSION=18.15.0
HOSTNAME=522b836f3f18
YARN_VERSION=1.22.19
SHLVL=1
HOME=/root
OLDPWD=/app/public
OPENAI_API_KEY="sk-****"
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
CODE="****"
PWD=/app
```

环境变量本身是存在的，但是应用并没有读取到
