### ISSUE TITLE
[Bug] Password code not working.

### ISSUE THREAD

**Issue by fliptoback** [Yidadaa/ChatGPT-Next-Web#2661]
Hi there,

I have deployed the container and it works well. Thank you!

But the CODE="my_secret_password"  doesnt work - I was expecting when i first load up the interface it would prompt me for a password? It doesnt.

How do I get this working?

My docker-compose.yaml looks like this:

```
version: '3.3'
services:
    chatgpt-next-web:
        ports:
            - '3002:3000'
        environment:
            - OPENAI_API_KEY="my_secret_API"
            - CODE="my_secret_password"
        image: yidadaa/chatgpt-next-web
        container_name: chatgpt
```
Thanks!
