### ISSUE TITLE
[Bug] 通过BASE_URL使用第三方接口时，请求报错，页面显式设置时可用

### ISSUE THREAD

**Issue by MomentDerek** [Yidadaa/ChatGPT-Next-Web#2772]
docker部署，使用其他第三方提供的接口，设置base_url后报错，但是在页面显式设置代理接口时可用

docker-compose文件
```
version: '3'
services:
  chatgpt-next-web:
    image: yidadaa/chatgpt-next-web
    restart: always
    ports:
      - 13000:3000
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - CODE=$CODE
      - BASE_URL=$BASE_URL
```

.env文件
```
# Your openai api key. (required)
OPENAI_API_KEY=sk-7y5TRW********

# Access passsword, separated by comma. (optional)
CODE=momincong

BASE_URL=https://next.aiplus.lol/api/openai
```

只设置base_url的情况下

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/40252940/b67e1b4a-df31-438e-bbca-98fa4bacd6b2)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/40252940/1b0bf91f-2792-4b83-b104-a4914f6afcf2)

在页面显式设置接口后，能成功请求

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/40252940/acf5f91e-c644-484a-915a-5434dacc6577)

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/40252940/268ae54a-9af8-4862-9906-8497aac3f6b0)

宝塔nginx配置（更改处）
```
    # location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    # {
    #     expires      30d;
    #     error_log /dev/null;
    #     access_log /dev/null;
    # }

    # location ~ .*\.(js|css)?$
    # {
    #     expires      12h;
    #     error_log /dev/null;
    #     access_log /dev/null;
    # }
    
    location / {
      proxy_pass http://127.0.0.1:13000/; 
      rewrite ^/(.*)$ /$1 break;
      proxy_redirect off;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Upgrade-Insecure-Requests 1;
      proxy_set_header X-Forwarded-Proto https;
      # 不缓存，支持流式输出
      proxy_cache off;  # 关闭缓存
      proxy_buffering off;  # 关闭代理缓冲
      chunked_transfer_encoding on;  # 开启分块传输编码
      tcp_nopush on;  # 开启TCP NOPUSH选项，禁止Nagle算法
      tcp_nodelay on;  # 开启TCP NODELAY选项，禁止延迟ACK算法
      keepalive_timeout 300;  # 设定keep-alive超时时间为65秒
    }
```

感谢作者
