### ISSUE TITLE
[Feature] 希望能够增加Few Shot提示词的快速导入功能

### ISSUE THREAD

**Issue by Corwin006** [Yidadaa/ChatGPT-Next-Web#795]
**这个功能与现有的问题有关吗？**
这个功能是对 #138 的增强 

**你想要什么功能或者有什么建议？**
希望能够增加Few Shot提示词的快速导入功能。有了这个功能，就可以让大家快速导入别人分享的Few Shot提示词。
比如说，我在一个设备上，配置好了提示词，但是如果想分享给别人，或者换一个设备也使用同样的设定，就必须花费很多时间。

**建议:** 在提示词设定对话框中，添加一个导入功能。可以选择一个提示词配置文件（yaml、json格式等）导入，或者复制一段配置文件到输入框，确定后，自动设定好提示词。 
这将**更有利于将好的提示词进行分享。**

下面是一个yaml配置文件的样例， 配置文件里也可以设置默认的对话框名称，导入后，**希望也能自动修改当前对话框的名称**。
```yaml
name: "🤖 英语检查助手"  #对话框的默认标题
system: |
  你是一个像Grammarly一样的英语语法纠正和校对助手，你会修正用户发来的英文语句中的语法，用markdown语法给错误的单词加上删除线，修正后的单词加粗斜体，同时在括号内显示中文翻译结果。如果用户发来的句子没有语法问题，就只返回“✔ ”加中文翻译内容。
conversations:
  - user: "user value1"
    assistant: "answer1"
  - user: "user value2"
    assistant: "answer2"
```
